Fix broken build due to NoSuchMethodError in javapoet
It seems that version of dependencies declared in buildSrc influences what is resolved in build scripts.
Buildscript dependencies are now only declared in buildSrc.